### ISSUE TITLE
Consider Use Of `pre-commit`

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [CDCgov/covid19-forecast-hub#145]
That `pre-commit` is not utilized in this repository arose in personal communication between the author and DHM. 

While some precaution is required to assure GitHub Action (GHA) workflows do not fail (e.g. ignoring `csv` files), these precautions do not seem difficult to implement. 

@sbidari together with DHM will make the final decision on whether this repository shall use `pre-commit`. This decision is not urgent.

<details markdown=1>

A lightweight `.pre-commit-config.yaml` file is _proposed_ here (note: hooks for R are missing; `csv` ignorings are not included, yet):

```yaml
repos:
################################################################################
# GENERAL
################################################################################
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=10000"]
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
################################################################################
# # GITHUB ACTIONS
# ################################################################################
# -   repo: https://github.com/rhysd/actionlint
#     rev: v1.7.4
#     hooks:
#     -   id: actionlint
################################################################################
# SPELLING
################################################################################
-   repo: https://github.com/crate-ci/typos
    rev: v1.28.1
    hooks:
    -   id: typos
        args: ["--force-exclude"]
################################################################################
# COMMIT MESSAGES
################################################################################
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0
    hooks:
    -   id: commitizen
################################################################################
``` 

The `_typos.toml` file:

```
[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
AFg6K7h4fhy2 = "AFg6K7h4fhy2"

[files]
extend-exclude = [
    "*.csv",
    ".gitignore",
    ".pre-commit-config.yaml",
    "./.github/ISSUE_TEMPLATE/*.md"]
```

</details>
